"""Response templates for intent labels across both classifier eras.

Original 88 entries vendored verbatim from
`intent_model/src/intent_model/intent_cli.py:21` (teammate-authored,
multilabel era). The trailing 33 entries are added for NN-classifier
labels used by EVA mode (22 vitals_* + 11 lowercase case-drift of the
CamelCase `Get_*` keys).

Each template has a `{value}` placeholder that the template_handler
factory fills from telemetry. Casing matches the classifier's label2id
exactly — collisions across eras are intentional aliases (same field,
different label name).
"""

INTENT_RESPONSE_TEMPLATES: dict[str, str] = {
    "Get_battery_level": "The rover battery level is {value}.",
    "Get_cabin_pressure": "The cabin pressure is {value}.",
    "Get_cabin_temperature_target": "The cabin temperature target is {value}.",
    "Get_coolant_pressure": "The coolant pressure is {value}.",
    "Get_coolant_storage": "The coolant storage is {value}.",
    "Get_distance_from_base": "The distance from base is {value}.",
    "Get_external_temp": "The external temperature is {value}.",
    "Get_fan_pri_rpm": "The primary fan RPM is {value}.",
    "Get_fan_sec_rpm": "The secondary fan RPM is {value}.",
    "Get_oxygen_pressure": "The oxygen pressure is {value}.",
    "Get_oxygen_storage": "The oxygen storage is {value}.",
    "Get_oxygen_tank": "The oxygen tank level is {value}.",
    "Get_primary_battery_level": "The primary battery level is {value}.",
    "Get_rover_elapsed_time": "The rover elapsed time is {value}.",
    "Get_scrubber_a_co2_storage": "Scrubber A CO2 storage is {value}.",
    "Get_scrubber_b_co2_storage": "Scrubber B CO2 storage is {value}.",
    "Get_secondary_battery_level": "The secondary battery level is {value}.",
    "Get_sim_running": "The simulation running status is {value}.",
    "get_Dust_connected": "The dust sensor connection status is {value}.",
    "get_battery_level_eva2": "The battery level for EVA 2 is {value}.",
    "get_brakes": "The brake setting is {value}.",
    "get_cabin_cooling": "The cabin cooling setting is {value}.",
    "get_cabin_heating": "The cabin heating setting is {value}.",
    "get_cabin_temperature": "The cabin temperature is {value}.",
    "get_co2_production_eva1": "The CO2 production for EVA 1 is {value}.",
    "get_co2_production_eva2": "The CO2 production for EVA 2 is {value}.",
    "get_coolant_gas_pressure_eva1": "The coolant gas pressure for EVA 1 is {value}.",
    "get_coolant_gas_pressure_eva2": "The coolant gas pressure for EVA 2 is {value}.",
    "get_coolant_liquid_pressure_eva1": "The coolant liquid pressure for EVA 1 is {value}.",
    "get_coolant_liquid_pressure_eva2": "The coolant liquid pressure for EVA 2 is {value}.",
    "get_coolant_storage_eva1": "The coolant storage for EVA 1 is {value}.",
    "get_coolant_storage_eva2": "The coolant storage for EVA 2 is {value}.",
    "get_distance_traveled": "The distance traveled is {value}.",
    "get_eva_elapsed_time_eva1": "The elapsed time for EVA 1 is {value}.",
    "get_eva_elapsed_time_eva2": "The elapsed time for EVA 2 is {value}.",
    "get_fan_pri_rpm_eva1": "The primary fan RPM for EVA 1 is {value}.",
    "get_fan_pri_rpm_eva2": "The primary fan RPM for EVA 2 is {value}.",
    "get_fan_sec_rpm_eva1": "The secondary fan RPM for EVA 1 is {value}.",
    "get_fan_sec_rpm_eva2": "The secondary fan RPM for EVA 2 is {value}.",
    "get_heading": "The heading is {value}.",
    "get_heart_rate_eva1": "The heart rate for EVA 1 is {value}.",
    "get_heart_rate_eva2": "The heart rate for EVA 2 is {value}.",
    "get_helmet_pressure_co2_eva1": "The helmet CO2 pressure for EVA 1 is {value}.",
    "get_helmet_pressure_co2_eva2": "The helmet CO2 pressure for EVA 2 is {value}.",
    "get_lidar": "The lidar reading is {value}.",
    "get_lights_on": "The lights-on status is {value}.",
    "get_oxy_consumption_eva1": "The oxygen consumption for EVA 1 is {value}.",
    "get_oxy_consumption_eva2": "The oxygen consumption for EVA 2 is {value}.",
    "get_oxy_pri_pressure_eva1": "The primary oxygen pressure for EVA 1 is {value}.",
    "get_oxy_pri_pressure_eva2": "The primary oxygen pressure for EVA 2 is {value}.",
    "get_oxy_pri_storage_eva1": "The primary oxygen storage for EVA 1 is {value}.",
    "get_oxy_pri_storage_eva2": "The primary oxygen storage for EVA 2 is {value}.",
    "get_oxy_sec_pressure_eva1": "The secondary oxygen pressure for EVA 1 is {value}.",
    "get_oxy_sec_pressure_eva2": "The secondary oxygen pressure for EVA 2 is {value}.",
    "get_oxy_sec_storage_eva1": "The secondary oxygen storage for EVA 1 is {value}.",
    "get_oxy_sec_storage_eva2": "The secondary oxygen storage for EVA 2 is {value}.",
    "get_pitch": "The pitch is {value}.",
    "get_primary_battery_level_eva1": "The primary battery level for EVA 1 is {value}.",
    "get_roll": "The roll is {value}.",
    "get_rover_pos_x": "The rover X position is {value}.",
    "get_rover_pos_y": "The rover Y position is {value}.",
    "get_rover_pos_z": "The rover Z position is {value}.",
    "get_scrubber_a_co2_storage_eva1": "Scrubber A CO2 storage for EVA 1 is {value}.",
    "get_scrubber_a_co2_storage_eva2": "Scrubber A CO2 storage for EVA 2 is {value}.",
    "get_scrubber_b_co2_storage_eva1": "Scrubber B CO2 storage for EVA 1 is {value}.",
    "get_scrubber_b_co2_storage_eva2": "Scrubber B CO2 storage for EVA 2 is {value}.",
    "get_secondary_battery_level_eva1": "The secondary battery level for EVA 1 is {value}.",
    "get_speed": "The speed is {value}.",
    "get_steering": "The steering angle is {value}.",
    "get_suit_pressure_co2_eva1": "The suit CO2 pressure for EVA 1 is {value}.",
    "get_suit_pressure_co2_eva2": "The suit CO2 pressure for EVA 2 is {value}.",
    "get_suit_pressure_other_eva1": "The other suit pressure for EVA 1 is {value}.",
    "get_suit_pressure_other_eva2": "The other suit pressure for EVA 2 is {value}.",
    "get_suit_pressure_oxy_eva1": "The suit oxygen pressure for EVA 1 is {value}.",
    "get_suit_pressure_oxy_eva2": "The suit oxygen pressure for EVA 2 is {value}.",
    "get_suit_pressure_total_eva1": "The total suit pressure for EVA 1 is {value}.",
    "get_suit_pressure_total_eva2": "The total suit pressure for EVA 2 is {value}.",
    "get_sunlight": "The sunlight reading is {value}.",
    "get_surface_incline": "The surface incline is {value}.",
    "get_temperature_eva1": "The temperature for EVA 1 is {value}.",
    "get_temperature_eva2": "The temperature for EVA 2 is {value}.",
    "get_throttle": "The throttle setting is {value}.",
    "set_cabin_cooling_off": "Cabin cooling has been set off with status {value}.",
    "set_cabin_cooling_on": "Cabin cooling has been set on with status {value}.",
    "set_cabin_heating_off": "Cabin heating has been set off with status {value}.",
    "set_cabin_heating_on": "Cabin heating has been set on with status {value}.",
    "set_lights_off": "Lights have been set off with status {value}.",
    "set_lights_on": "Lights have been set on with status {value}.",

    # NN-classifier vitals_* labels (EVA mode, suit-side telemetry)
    "vitals_heart_rate": "The heart rate is {value} beats per minute.",
    "vitals_temperature": "The body temperature is {value}.",
    "vitals_oxy_pri_storage": "The primary oxygen storage is {value}.",
    "vitals_oxy_sec_storage": "The secondary oxygen storage is {value}.",
    "vitals_oxy_pri_pressure": "The primary oxygen pressure is {value}.",
    "vitals_oxy_sec_pressure": "The secondary oxygen pressure is {value}.",
    "vitals_suit_pressure_total": "The total suit pressure is {value}.",
    "vitals_suit_pressure_oxy": "The suit oxygen pressure is {value}.",
    "vitals_suit_pressure_co2": "The suit CO2 pressure is {value}.",
    "vitals_suit_pressure_other": "The other suit pressure is {value}.",
    "vitals_helmet_pressure_co2": "The helmet CO2 pressure is {value}.",
    "vitals_fan_pri_rpm": "The primary fan RPM is {value}.",
    "vitals_fan_sec_rpm": "The secondary fan RPM is {value}.",
    "vitals_scrubber_a_co2_storage": "Scrubber A CO2 storage is {value}.",
    "vitals_scrubber_b_co2_storage": "Scrubber B CO2 storage is {value}.",
    "vitals_coolant_storage": "The coolant storage is {value}.",
    "vitals_coolant_gas_pressure": "The coolant gas pressure is {value}.",
    "vitals_coolant_liquid_pressure": "The coolant liquid pressure is {value}.",
    "vitals_oxy_consumption": "The oxygen consumption is {value}.",
    "vitals_co2_production": "The CO2 production is {value}.",
    "vitals_oxy_time_left": "The oxygen time remaining is {value}.",
    "vitals_batt_time_left": "The battery time remaining is {value}.",

    # NN-classifier lowercase aliases for the CamelCase rover Get_* keys above
    "get_battery_level": "The rover battery level is {value}.",
    "get_cabin_pressure": "The cabin pressure is {value}.",
    "get_coolant_pressure": "The coolant pressure is {value}.",
    "get_coolant_storage": "The coolant storage is {value}.",
    "get_external_temp": "The external temperature is {value}.",
    "get_fan_pri_rpm": "The primary fan RPM is {value}.",
    "get_fan_sec_rpm": "The secondary fan RPM is {value}.",
    "get_oxygen_pressure": "The oxygen pressure is {value}.",
    "get_oxygen_tank": "The oxygen tank level is {value}.",
    "get_rover_elapsed_time": "The rover elapsed time is {value}.",
    "get_distance_from_base": "The distance from base is {value}.",
    "get_co2_scrubber": "The CO2 scrubber storage is {value}.",
}
